### ISSUE TITLE
Looks like wrong width of img

### ISSUE THREAD

**Issue by metelkin** [pages-themes/slate#4]
For mobile divices big figures spoile the view.
I suppose the missprint is here:
_sass/jekyll-theme-slate.scss

img{
...
max-width: 739px; /* max-width: 100% ??? */
...
}

**Comment by Edditoria** [comment]
Same problem here.

The push request #3 was merged, and suppose the scss style is fixed in Github. But I didn't notice until you raise this issue (Thanks!)

I think the problem still exists because the gem is not update yet?

No choice but a quick fix can solve it. Please add the following styles to `style.scss`

```scss
// Temp Fix for Slate theme gem for Github Pages

@media screen and (max-width: 992px) {
  img {
    max-width: 100%;
  }
}
```

The above code is exactly the same in the PR. I did this in every Pages anyway.

I have created the repo for quick test:

Repo: [https://github.com/Edditoria/gh-pages-slate-theme-test]()
Pages preview: [https://edditoria.github.io/gh-pages-slate-theme-test/]()

Happy coding!

> sorry for bad English
