### ISSUE TITLE
Superscript tags broken by CSS

### ISSUE THREAD

**Issue by nic-hartley** [pages-themes/slate#40]
I wanted to include superscript (`<sup></sup>`) in some text. The tag itself carries through, as expected, but the Slate theme includes this CSS reset (removed the other tags it affects, which AFAICT is all of them):

```css
sup {
    margin: 0;
    padding: 0;
    border: 0;
    font: inherit;
        font-weight: inherit;
        font-size: inherit;
    vertical-align: baseline;
}
```

There's no corresponding re-setup for `sup`, so it ends up just looking like normal text.

One fix would be to add this to the bottom of the stylesheet:

```css
sup {
    font-size: 65%;
    vertical-align: super;
    font-weight: bold;
}
```

...but of course that might need tweaking to fit better in the theme. I dunno, I'm not an artist. I just want my footnotes.
