### ISSUE TITLE
Can't run gh-pages Slate theme locally on my desktop

### ISSUE THREAD

**Issue by peterpoliwoda** [pages-themes/slate#53]
I'm a little stuck here, it might not be a problem with the slate theme per se, potentially my config or I'm missing something obvious. The page builds fine through Github, but locally I'm getting a Sass error:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    File to import not found or unreadable: jekyll-theme-slate. on line 1
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.7.0/bin/jekyll)
```

Looks like Saas can't find my theme through the @import 

The CSS file looks normal: 

```CSS
---
---
@import "jekyll-theme-slate";

a:hover {
    font-weight: normal;
}

...

```

Am I missing something obvious like installing the theme locally or something like that?
