### ISSUE TITLE
Build script broken by newer version of rubocop

### ISSUE THREAD

**Issue by rdipardo** [pages-themes/slate#54]
Just reporting that I can locally reproduce the error output [of this failed build](https://travis-ci.org/github/pages-themes/slate/builds/716171951#L359) with the following environment:

    $ bundle list | awk '/slate /'
      * jekyll-theme-slate (0.1.1)
    $ ruby -v
    ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

The problem is that running `script/bootstrap` installs a recent version of `rubocop`:

    $ bundle list | awk '/rubocop /'
      * rubocop (0.93.1)

The linting step in `script/cibuild` fails because `rubocop` has added some fussy new cops that aren't being filtered.
Similar to #39, this can be easily fixed by updating `.rubocop.yml`. Here's a config that works:

```yaml
AllCops:
  NewCops: enable
  Exclude:
    - _site/**/*
Layout/LineLength:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
```
